### ISSUE TITLE
config file needs to be updated

### ISSUE THREAD

**Issue by michaelaye** [michaelaye/nbplanetary#1]
As reported by @mschwamb :

```python
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr
from dask import compute, delayed
from p4_data_ingestion.manifests import create_manifest, merge_secret_manifest_with_hirise_index
from planetarypy.hirise import RGB_NOMAP, RGB_NOMAPCollection
from skimage.exposure import rescale_intensity
from skimage.io import imsave
from skimage.util import img_as_ubyte
from tqdm.auto import tqdm
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/pds/indexes.py", line 234, in set_url
    self.url = config.get_value(self.key)["url"] if url is None else url
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/config.py", line 66, in get_value
    return reduce(lambda c, k: c[k], key.split("."), self.d)
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/config.py", line 66, in <lambda>
    return reduce(lambda c, k: c[k], key.split("."), self.d)
KeyError: 'missions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mes/python/p4/p4_ingestion_pipeline/p4_create_subjects.py", line 8, in <module>
    from planetarypy.hirise import RGB_NOMAP, RGB_NOMAPCollection
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/hirise.py", line 25, in <module>
    rdrindex = get_index("mro.hirise.indexes.rdr")
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/pds/apps.py", line 41, in get_index
    index = Index(key)
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/pds/indexes.py", line 228, in __init__
    self.set_url(url)
  File "/home/mes/anaconda3/envs/p4/lib/python3.9/site-packages/planetarypy/pds/indexes.py", line 236, in set_url
    self.url = dynamic_urls[self.instrument_key]().latest_index_label_url
KeyError: 'mro.hirise'
```

**Comment by michaelaye** [comment]
This was done be recent version.
