### ISSUE TITLE
Package execnb missing in dependencies

### ISSUE THREAD

**Issue by swalterfub** [michaelaye/nbplanetary#46]
`from execnb.nbio import write_nb` throws `ModuleNotFoundError: No module named 'execnb'`
After `pip install execnb` it works.

**Comment by michaelaye** [comment]
How did you create this error? At what moment did it happen?

**Comment by cjtu** [comment]
Repro on Ubuntu 22.04:

- fresh conda env: conda create -n plpy -c conda-forge python=3.12 pip gdal
- pip install planetarypy
- `from planetarypy.pds.apps import get_index`

```Python
Traceback (most recent call last):
  File "/home/cjtu/projects/planetarypy/var/test.py", line 1, in <module>
    from planetarypy.pds.apps import get_index
  File "/home/cjtu/miniforge3/envs/plpy2/lib/python3.12/site-packages/planetarypy/pds/apps.py", line 9, in <module>
    from .indexes import Index
  File "/home/cjtu/miniforge3/envs/plpy2/lib/python3.12/site-packages/planetarypy/pds/indexes.py", line 20, in <module>
    from .. import utils
  File "/home/cjtu/miniforge3/envs/plpy2/lib/python3.12/site-packages/planetarypy/utils.py", line 24, in <module>
    from execnb.nbio import write_nb
ModuleNotFoundError: No module named 'execnb'
```

Works after pip install execnb

**Comment by Meistermagier** [comment]
Bumping this error up had this when trying to pip install in a conda environment after previously installing geopandas.

Windows 11

- fresh install conda env 
- conda install geopandas
- pip install planetarypy
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], [line 1](vscode-notebook-cell:?execution_count=3&line=1)
----> [1](vscode-notebook-cell:?execution_count=3&line=1) from planetarypy.pds import utils

File [c:\Users\diese\mambaforge\envs\geo_env\Lib\site-packages\planetarypy\pds\utils.py:15](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/pds/utils.py:15)
     [13](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/pds/utils.py:13) import pvl
     [14](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/pds/utils.py:14) from fastcore.utils import Path
---> [15](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/pds/utils.py:15) from .. import utils
     [17](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/pds/utils.py:17) # %% ../../notebooks/api/02f_pds.utils.ipynb 4
     [18](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/pds/utils.py:18) class IndexLabel:

File [c:\Users\diese\mambaforge\envs\geo_env\Lib\site-packages\planetarypy\utils.py:24](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/utils.py:24)
     [22](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/utils.py:22) import requests
     [23](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/utils.py:23) from astropy.time import Time as ASTROTIME
---> [24](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/utils.py:24) from execnb.nbio import write_nb
     [25](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/utils.py:25) from requests.auth import HTTPBasicAuth
     [26](file:///C:/Users/diese/mambaforge/envs/geo_env/Lib/site-packages/planetarypy/utils.py:26) from tqdm.auto import tqdm

ModuleNotFoundError: No module named 'execnb'`

**Comment by michaelaye** [comment]
Removed this odd dependendy for 0.31.2 (now on pypi), i must have been feverish to put such odd tool into plpy.
Fixed by https://github.com/michaelaye/nbplanetary/commit/90c6c70cdbdc3e4fd032aac95f9acfcb0db7d30e
