### ISSUE TITLE
pds.apps.get_index AttributeError: 'URL' object has no attribute 'split'

### ISSUE THREAD

**Issue by swalterfub** [michaelaye/nbplanetary#63]
```
>>> from planetarypy.pds.apps import get_index
>>> ctrindex=get_index("mro.ctx", "edr")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/planet/mambaforge/envs/plpy/lib/python3.11/site-packages/planetarypy/pds/apps.py", line 34, in get_index
    if not index.local_table_path.exists() or force:
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/software/planet/mambaforge/envs/plpy/lib/python3.11/site-packages/planetarypy/pds/indexes.py", line 142, in local_table_path
    return self.local_dir / self.table_filename
                            ^^^^^^^^^^^^^^^^^^^
  File "/software/planet/mambaforge/envs/plpy/lib/python3.11/site-packages/planetarypy/pds/indexes.py", line 125, in table_filename
    return self.label_filename.with_suffix(self.tab_extension)
           ^^^^^^^^^^^^^^^^^^^
  File "/software/planet/mambaforge/envs/plpy/lib/python3.11/site-packages/planetarypy/pds/indexes.py", line 111, in label_filename
    return Path(self.url.split("/")[-1])
                ^^^^^^^^^^^^^^
AttributeError: 'URL' object has no attribute 'split'
```

**Comment by swalterfub** [comment]
Sorry was using outdated version 0.30.0
